import LegalPage from "../components/LegalPage";

const TermsOfUse = () => (
  <LegalPage
    title="Terms of Use"
    description="Terms of Use for the VetanNow platform operated by Anika Financial Technologies Private Limited."
    path="/terms"
  >
    <section>
      <h2>1. Introduction</h2>
      <p>
        Anika Financial Technologies Private Limited (hereinafter referred to as "the Company"),
        through its Website and Mobile Application called "VetanNow" runs a financial wellness
        platform that allows the Employee/Gig Worker/Pensioner users to track their salary/Earned
        Amount/pension and enables them to withdraw on credit, the accrued salary/Earned
        Amount/pension at any point of time at an agreed transaction fees which credit is extended by
        Non-Banking Financial Companies with whom VetanNow has arrangements.
      </p>
      <p>
        By clicking "Join Now", "Sign Up", registering, accessing or using the VetanNow Platform, you
        agree to enter into a legally binding contract and be bound by the present Terms of Use. If you
        do not agree to any of the Terms of Use, you should not click "Join Now" (or similar) and should
        not access or otherwise use the VetanNow platform or the Product and Services. If you wish to
        terminate this agreement at any time, it can be done by closing the user account and no longer
        accessing or using the VetanNow platform or Products and Services.
      </p>
      <p>
        Even otherwise, when you use the VetanNow platform, you agree to all of these Terms of Use. The
        use of the VetanNow Platform is also subject to VetanNow's other policies including but not
        limited to the Privacy Policy which covers how VetanNow collects, uses, shares and stores
        personal information of users.
      </p>
      <p>
        You acknowledge that you have read these Terms of Use, the other Policies including but not
        limited to Privacy Policy and agree to all its terms and conditions.
      </p>
      <p>
        VetanNow reserves the right, at its sole discretion, to change, modify, add or remove portions of
        these Terms of Use. We shall notify You of any updates or changes in the Terms of Use. Post such
        notification, it shall be your responsibility to review the updated Terms of Use. Your continued
        use of the VetanNow platform following the posting of changes to the Terms of Use and the
        aforementioned notification shall be deemed to mean that you have reviewed the updated Terms of
        Use and accept and agree to the updated Terms of Use.
      </p>
      <p>
        VetanNow reserves the right to terminate Your Account/this agreement and/or refuse to provide You
        with access to the VetanNow platform if it is brought to VetanNow's notice or if it is discovered
        that you are not eligible to use the VetanNow platform.
      </p>
      <p>
        These Terms of Use shall be deemed to be an electronic record laying down the mutually acceptable
        terms for use of VetanNow platform by You. Being an electronic record generated by or through a
        computer system, it does not require any physical or digital signatures.
      </p>
    </section>

    <section>
      <h2>2. Definitions</h2>
      <ol>
        <li>
          "Employee" shall mean any person employed in full time service with the Employer, having a
          minimum service/employment history of 3 months with the Employer and a fixed salary.
        </li>
        <li>
          "Gig Worker" shall mean any person who performs work or participates in a work arrangement and
          earns from such activities outside the traditional employer-employee relationship.
        </li>
        <li>
          "Employer" shall mean any organization or entity who employs the User Employee, or who pays
          Pension to the Pensioner with whom VetanNow has a separate agreement for facilitating extension
          of Advance Facility and who has agreed to repay the Advance Facility to the NBFC by debiting
          the salary/pension of the User Employee/pensioner, on behalf of the User Employee/pensioner.
        </li>
        <li>
          "Gig Platform" shall mean any organization or entity on whose platform the Gig Worker is
          registered, with whom VetanNow has a separate agreement for facilitating the extension of
          Earned Amount Access from the NBFC to the Onboarded Gig Worker and who has agreed to repay the
          Repayable Amount to the NBFC by debiting the Earned Amount of the Onboarded Gig Worker, on
          behalf of the Onboarded Gig Worker.
        </li>
        <li>
          "NBFC" shall mean the Non Banking Financial Company who has agreed to consider to extend the
          Salary/Earned Amount Advance Facility to the User Employee/Onboarded Gig Worker subject to the
          User Employee/Onboarded Gig Worker executing the Salary Advance/Earned Amount Facility Documents
          and paying the Transaction Fees.
        </li>
        <li>
          "Transaction Fees" shall mean the charges payable by the User Employee/Onboarded Gig Worker to
          the NBFC for availing the Salary/Earned Amount Advance Facility.
        </li>
        <li>
          "Products and Services" shall mean products, features, services, technologies, software etc.
          that are being offered on the VetanNow platform.
        </li>
        <li>"Pensioner" means and includes a former employee who is currently drawing pension from the Employer.</li>
        <li>
          "Repayment Account" shall mean a bank account designated by the NBFC for collection of all the
          sum of money due to be repaid by the User Employees/Onboarded Gig Workers and wherein the
          Employer/Gig Platform would deposit the said sums after deducting the same from the salary of
          the User Employee/Onboarded Gig Worker.
        </li>
        <li>
          "Salary/Earned Amount/Advance Facility" shall mean the amount sanctioned in the form of
          loan/credit facility as advance salary/Earned Amount/Pension subject to appraisal by the NBFC
          and VetanNow and agreed to be disbursed to the User Employee/Onboarded Gig Worker by the NBFC as
          per Salary/Earned Amount Advance Facility Documents; irrespective of whether such disbursement
          is in whole or parts, as per the request of the User Employee/Onboarded Gig Workers through the
          platform belonging to VetanNow.
        </li>
        <li>
          "Salary/Earned Amount/Advance Facility Documents" shall mean the Agreements or any other
          document (as amended, restated or modified from time to time) executed by the User
          Employee/Onboarded Gig Worker with the NBFC for the grant of Salary/Earned Amount Advance
          Facility, capturing the terms and conditions for the grant of Salary/Earned Amount Advance
          Facility by the NBFC including but not limited to loan application, facility/loan/credit
          facility agreement, security documents, etc. or any other document stipulated by the NBFC from
          time to time.
        </li>
        <li>
          "User Employee" shall mean any Employee employed with the Employer, who are registered users of
          the VetanNow platform and have agreed to draw advance salary by availing Salary Advance Facility
          from the NBFC, on the basis of leads/reports generated by the VetanNow platform.
        </li>
        <li>
          "Onboarded Gig Workers" shall mean Gig Workers of the Gig Platform who are registered users of
          the VetanNow Platform and have agreed to draw advance Earned Amount by availing Earned Amount
          Advance Facility from the NBFC, on the basis of leads/reports generated by VetanNow.
        </li>
        <li>
          "Earned Amount" shall only include the approved earnings of the Gig Workers that flow from the
          Gig Platform and shall not include Cash on Delivery payments, unless otherwise agreed in writing
          by the Parties. Earnings corresponding to an approved task shall automatically be counted
          towards Earned Amounts.
        </li>
        <li>"Pension" shall mean and include the recurring monthly payments paid to a Pensioner by the Employer.</li>
        <li>"Salary" shall mean and include the net in-hand monthly salary.</li>
        <li>"Users" shall mean and include all registered users of the Platform.</li>
      </ol>
      <p>
        These Terms of Use set out the binding terms and conditions for use by a User Employee/Onboarded
        Gig Worker ("You") of the VetanNow platform and the related Services as defined herein below.
      </p>
    </section>

    <section>
      <h2>3. Acceptance of Terms of Use</h2>
      <p>
        VetanNow platform along with the Products and Services are licensed and not sold (hereinafter
        together referred to as "the License") to You for use only and solely in line with the present
        Terms of Use.
      </p>
      <p>
        The terms VetanNow and the Company are used interchangeably in the Terms since VetanNow is a
        platform owned and run by the Company.
      </p>
    </section>

    <section>
      <h2>4. Account Creation</h2>
      <ol>
        <li>
          In order to use the VetanNow platform and Product and Services, you will be required to create
          an account ("Account"). As part of the Account opening process, you have to provide your name,
          gender, date of birth, age, phone number, photograph, other personal details, an e-mail address
          and a password etc. which is to be used for logging into the Account in the future. Further, in
          order to avail the Salary/Earned Amount Advance Facility, You will have to inter alia provide
          details including but not limited to your employee identification number with the Employer,
          official email id, your employment history with the Employer, attendance details and KYC details
          (PAN, Aadhaar Card, Address Proof, Salary Slip, account details and bank statements, income tax
          returns etc.), if You are a User Employee.
        </li>
        <li>
          You hereby agree and undertake that you will not transfer or share your Account details and
          password with anyone. The confidentiality of your username and password is to be maintained by
          you as your sole responsibility and in case of any misuse or unauthorised access of the Account
          you shall be solely liable for the same. Further, in case of any such misuse or unauthorized
          access it would be your responsibility to immediately inform and notify VetanNow.
        </li>
      </ol>
    </section>

    <section>
      <h2>5. User eligibility and the conditions of use</h2>
      <p>You explicitly agree, represent and warrant that you:</p>
      <ol>
        <li>
          Can enter into legally binding contracts, are not "incompetent to contract" under the Indian
          Contract Act, 1872 and have the capacity to enter into the present contract.
        </li>
        <li>Shall not give access to your respective Account to others or transfer the Account to anyone else.</li>
        <li>You or your Account has not previously been disabled by VetanNow for violations of its terms or policies.</li>
        <li>
          Are not prohibited from using the VetanNow platform or the Products and Services under
          applicable laws or orders, directions or judgments of courts.
        </li>
        <li>Shall not do anything that is unlawful, misleading, discriminatory or fraudulent.</li>
        <li>
          Shall not upload viruses or malicious code, or do anything that could disable, overburden or
          impair the proper working or appearance of the VetanNow platform or interfere with or circumvent
          the security features of the VetanNow Platform or the Products and Services or any related
          mobile application, other mobile applications, or the Internet.
        </li>
        <li>
          Shall not access or collect data from the VetanNow platform using automated means or attempt to
          access data for which there is no permission to access.
        </li>
        <li>Shall not breach these Terms or any other Terms and policies that apply to use of the VetanNow platform.</li>
        <li>
          Agree, undertake and covenant that, during the use of the VetanNow platform, you shall not use,
          host, display, upload, modify, amend, publish, transmit, update or share any information or
          content including but not limited to User Content that:
          <ol>
            <li>Belongs to another person or entity and in relation to which you do not have any right.</li>
            <li>
              Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic,
              libellous, invasive of another person's privacy, hateful or racially or ethnically
              objectionable, or encouraging money laundering or gambling, or otherwise unlawful in any
              manner whatsoever.
            </li>
            <li>Is misleading or false in any way.</li>
            <li>
              Involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or
              "spamming".
            </li>
            <li>
              Infringes upon or violates any third party's rights including, but not limited to,
              intellectual property rights, rights of privacy (including without limitation unauthorized
              disclosure of a person's name, e-mail address, physical address, phone number, photographs)
              or rights of publicity.
            </li>
            <li>
              Provides instructional information about illegal activities such as violating someone's
              privacy, or providing or creating computer viruses and malware such as spyware, worms,
              trojans, etc.
            </li>
            <li>
              Tries to gain unauthorized access or exceeds the scope of authorized access to the VetanNow
              platform or to account information of other Users etc.
            </li>
            <li>
              Engages in commercial or business activities including but not limited to activities for
              gain, contests, sweepstakes, barter, advertising etc.
            </li>
            <li>Interferes with another user's use of the VetanNow Platform.</li>
            <li>
              Contains software viruses or any other computer codes, files or programs designed to
              interrupt, destroy or limit the functionality of any computer resource; or contains any
              trojan horses, worms or other computer programming routines that may damage, detrimentally
              interfere with, diminish value of, covertly intercept or steal any system, data or personal
              information.
            </li>
            <li>Harms minors in any way.</li>
            <li>
              Threatens the unity, integrity, defense, security or sovereignty of India, friendly
              relations with foreign states, or public order or causes incitement to the commission of any
              cognizable offence or prevents investigation of any offence or is insulting to any other
              nation.
            </li>
            <li>Is a misuse or unauthorized use of the VetanNow platform or is a use prohibited by law or is unlawful.</li>
          </ol>
        </li>
      </ol>
    </section>

    <section>
      <h2>6. Availing the Products and Services</h2>
      <ol>
        <li>
          You may, after opening an Account on the VetanNow platform, apply for Salary/Earned Amount
          Advance Facility by submitting your request on the VetanNow platform through a form on the
          VetanNow platform which shall contain the details of the proposed Salary/Earned Amount Advance
          Facility including but not limited to the amount, the date of repayment, mode of disbursement
          etc. (hereinafter referred to as the "Application Form").
        </li>
        <li>
          As a part of the application for Salary/Earned Amount Advance Facility you shall be required to
          provide details and documents relating, including but not limited to, income, pension,
          employment or professional status, and such other information as the NBFC may require in terms
          of the KYC Regulations applicable to it ("Preliminary Information").
        </li>
        <li>
          You hereby also authorize the NBFC and VetanNow to share relevant information including Personal
          Data with third parties to get your credit information report from one or more credit
          information companies, from time to time.
        </li>
        <li>
          You shall also be required to sign and execute the Salary/Earned Amount Advance Facility
          Documents, as may be required by the NBFC, from time to time.
        </li>
        <li>
          The Application Form, Preliminary Information, Salary/Earned Amount Advance Facility Documents
          and other reports/information shall thereafter be provided to the NBFC for the purpose of KYC
          and e-KYC verification and/or to such other verification by any agency such as lawyers, search
          clerks, accountants or valuers as may be appointed or designated by the NBFC.
        </li>
        <li>
          Pursuant thereto and subject to due diligence/approval by the NBFC, the Salary/Earned Amount
          Advance Facility may be extended to You subject to your agreeing to pay the Transaction Fees as
          provided for in the Salary/Earned Amount Advance Facility Documents.
        </li>
        <li>
          You agree and understand that the Salary/Earned Amount Advance Facility would be extended
          strictly in terms of the Salary/Earned Amount Facility Documents executed between You and the
          NBFC, along with the present Terms of Use and the Privacy Policy.
        </li>
        <li>
          You hereby also irrevocably authorize the Employer/Gig Platform to deduct the amount of the
          Salary/Earned Amount Advance Facility, interest accrued thereon as per the Salary/Earned Amount
          Advance Facility Documents and the Transaction Fees, whenever the same are due as per the
          Salary/Earned Amount Advance Facility and deposit the same in the Repayment Account as
          designated by the NBFC.
        </li>
        <li>
          The present Terms of Use, Privacy Policy, Application Form, Salary/Earned Amount Advance
          Facility Documents and all other documents executed by You shall form the entire understanding
          for the purpose of extension of the Products and Services.
        </li>
      </ol>
    </section>

    <section>
      <h2>7. License and its scope</h2>
      <p>
        As long as You comply with these Terms of Use and other policies including but not limited to
        Privacy Policy, VetanNow grants you a personal, revocable, non-exclusive, non-transferable,
        limited privilege to access and use the VetanNow platform and Product and Services.
      </p>
      <p>
        You may not rent, lease, lend, sell, redistribute, sublicense or exploit in any manner
        (commercial or otherwise), the VetanNow platform for any purpose including but not limited to any
        business or commercial use. You may not copy, decompile, reverse engineer, disassemble, attempt
        to derive the source code of, modify, or create derivative works of the VetanNow platform and/or
        Products and Services, any updates or any part thereof. The terms of this License will govern any
        upgrades provided that replace and/or supplement the original VetanNow platform and/or Products
        and Services, unless such upgrade is accompanied by a separate license in which case the present
        Terms of Use and the terms of the license for that upgrade will govern.
      </p>
    </section>

    <section>
      <h2>8. Specific permissions, consent and authorizations given by you</h2>
      <p>You hereby agree, permit, consent, authorize and provide:</p>
      <ul>
        <li>
          A non-transferable, non-sublicensable and limited right to VetanNow to use, store, copy, update,
          process, and share information, details, documents etc. relating to you, that you provide on or
          through the VetanNow Platform with your voluntary and informed consent solely to provide the
          earned wage advance facility. You agree and provide your consent to share your information
          accessed by VetanNow provided on or through the VetanNow Platform for providing the earned wage
          advance facility, for the following purposes: extending and facilitating the earned wage advance
          facility; KYC verification and authentication by agencies duly authorised by VetanNow; legal and
          regulatory purposes; and providing you an improved and a better user experience. Further,
          sharing of your information with any third party for purposes except as outlined above shall be
          subject to prior intimation and your consent.
        </li>
      </ul>
      <ol>
        <li>
          Consent and authorize the Employer/Gig Platform to share the required data, that may include
          Your attendance data, projects worked on and other such details (in case of Gig Platform) to
          enable calculation of maximum Salary/Earned Amount Advance Facility that You may be eligible to
          draw.
        </li>
        <li>
          Consent to receive all communications at the mobile number provided, even if this mobile number
          is registered under the DND/NCPR list under TRAI regulations. And for that purpose, You further
          authorize the Company to share/disclose the information to any third party service provider or
          any affiliates, group companies, their authorized agents, or third-party service providers.
        </li>
        <li>
          Consent to using a third party service to verify KYC details including PAN (through NSDL or
          other portals), phone number and bank account.
        </li>
        <li>
          Specific consent to share the Application Form, Preliminary Information, all other details and
          information relating to You including personal information and KYC documents etc. with the NBFC.
        </li>
        <li>
          Consent to collect and share the duly executed Salary/Earned Amount Advance Facility Documents,
          repayment cheques/NACH/ECS etc., with the NBFC, on your behalf.
        </li>
        <li>
          Consent to the receipt of communication from VetanNow or the NBFC by way of, including but not
          limited to SMS, e-mails, WhatsApp and newsletters. This consent and permission shall supersede
          and prevail over any preferences set or registration done with the Do Not Disturb (DND
          Register)/ National Customer Preference Register (NCPR).
        </li>
        <li>
          Consent to the Company to access and use for the purposes as outlined in this Privacy Policy,
          device-related information which includes but is not limited to device ID, IP address, hardware
          model, operating system and version, device name, unique device identifier, mobile network
          information, and details about the device's interaction with the services being offered by the
          Company from time to time.
        </li>
        <li>
          Irrevocably authorize the Employer/Gig Platform to deduct, at source, the amount of the
          Salary/Earned Amount Advance Facility, interest accrued thereon as per the Salary/Earned Advance
          Facility Documents (if any) and the Transaction Fees and deposit the same in the Repayment
          Account designated by the NBFC towards repayment to the NBFC.
        </li>
        <li>
          Permission to track your location and any unusual frequent changes in location, in order to
          ensure that the repayment of the Salary/Earned Advance Facility, interest accrued thereon as per
          the Salary/Earned Advance Facility Documents and the Transaction Fees can be pursued and
          ensured. The said tracking shall continue during the provision of the Products and Services, and
          even in case You discontinue, stop or cease to use or avail the Products and Services, through
          deletion or uninstallation of the VetanNow platform or otherwise, till the event the amount due
          to the NBFC stands repaid in full.
        </li>
        <li>
          Consent to receive sponsored content and show ads that VetanNow thinks will be relevant to you.
          VetanNow may use Your personal data and/or information to help determine which ads to show to
          You.
        </li>
        <li>
          VetanNow may access and use the mobile contact book of the user from their hand-held device to
          empower users to share the app with their coworkers and promote financial wellness at work.
        </li>
        <li>End user consents to the collection and usage of their publicly available data.</li>
      </ol>
    </section>

    <section>
      <h2>9. Intellectual Property Rights belonging to VetanNow</h2>
      <p>
        These Terms of Use do not transfer to you any Intellectual Property Rights and other proprietary
        information including but not limited to copyright, trademarks, service marks, graphics and logos
        used in or in connection with the VetanNow platform or the Products and Services. The said
        Intellectual Property Rights are owned by VetanNow or third parties and all rights, titles, and
        interests in and to such property will remain solely with the VetanNow platform or third parties,
        as the case may be. Your use of the VetanNow Platform or Products and Services grants you no right
        or license to reproduce or otherwise use any VetanNow or third-party Intellectual Property Rights.
      </p>
      <p>
        You cannot copy, post, distribute, or reproduce in any way any copyrighted material, trademarks or
        other proprietary information of VetanNow, third parties etc.
      </p>
    </section>

    <section>
      <h2>10. Links to Third Party Applications or Websites</h2>
      <p>
        The VetanNow platform may contain links and interactive functionality interacting with the
        websites or applications of third parties including but not limited to payment gateways, links to
        advertisements etc.
      </p>
      <p>
        VetanNow is not responsible for and has no liability for the functionality, actions, inactions,
        privacy settings, privacy policies, terms, or content of any such third party website or
        application. VetanNow shall not be liable or responsible for any such interactions that you may
        have with any such third party websites, applications or links etc.
      </p>
    </section>

    <section>
      <h2>11. Disclaimer of warranties and liabilities</h2>
      <p>
        You expressly acknowledge and agree that use of the VetanNow Platform or the Products and Services
        is at your sole risk and that the entire risk as to satisfactory quality, performance, accuracy
        etc. is with you. The VetanNow platform and the Products and Services are provided on an "as is"
        and "as available" basis, with all faults and without warranty of any kind.
      </p>
      <p>
        VetanNow hereby disclaims all warranties and conditions with respect to the VetanNow platform and
        Products and Services, either express or implied including, but not limited to the implied
        warranties and/or conditions of merchantability, of satisfactory quality, of fitness for a
        particular purpose, of accuracy, of quiet enjoyment and non-infringement of third party rights.
        VetanNow does not warrant against interference with your enjoyment of the VetanNow platform and
        Products and Services, that the functions contained in, or services performed or provided by the
        VetanNow platform will meet your requirements, that the operation of the VetanNow platform or
        Products and Services will be without delays, disruption or imperfections, uninterrupted or
        error-free, or that defects in the VetanNow platform will be corrected. VetanNow shall not be
        liable under any circumstances for damages arising out of or related in any way to your inability
        to access, or your difficulty in accessing the VetanNow platform, any hacking attacks, malware
        infection, bugs, viruses, trojans, or the like, which may be transmitted to or through the
        VetanNow platform by any third party (even though all efforts will be made to secure the VetanNow
        platform); any loss of your data or your failure to keep your password or Account details secure
        and confidential.
      </p>
      <p>
        VetanNow shall have no responsibility for any damage to your mobile handset or computer system or
        loss of data that results from the download of any content, materials, document or information.
      </p>
      <p>
        The VetanNow platform may contain views, advices and statements of third parties but VetanNow does
        not endorse the accuracy or reliability of any views, advices or statements. You relying on any
        such views, advices and statements shall be solely at your risk and cost.
      </p>
    </section>

    <section>
      <h2>12. Limitation of liability</h2>
      <p>
        To the extent not prohibited by law, in no event shall VetanNow be liable for personal injury or
        any exemplary, incidental, special, indirect or consequential damages whatsoever, including,
        without limitation, damages for loss of profits, loss of data, information, content, personal
        loss, business interruption or any other commercial damages or losses, arising out of or related
        to your use or inability to use the VetanNow platform or Products and Services, however caused,
        regardless of the theory of liability (contract, tort or otherwise) and even if VetanNow has been
        advised of the possibility of such damages. Notwithstanding anything contained herein or the
        Privacy Policy or any other policy, in no event shall VetanNow's total liability to you for all
        and any damages, losses, claims etc. exceed the amount of Transaction Fees paid by you to the
        NBFC for availing the Salary/Earned Amount Advance Facility.
      </p>
    </section>

    <section>
      <h2>13. Indemnification</h2>
      <p>
        You agree to indemnify and hold VetanNow and its affiliates, directors, officers, employees, and
        agents harmless from and against any liabilities, losses, damages or costs, including reasonable
        attorneys' fees incurred in connection with or arising from your breach of any of the Terms of
        Use or other policies including but not limited to the Privacy Policy and any third-party
        allegations, claims, actions, disputes or demands asserted by any of them as a result of or
        relating to your use of the VetanNow platform and Products and Services or breach of any of the
        present Terms of Use or other policies including but not limited to the Privacy Policy.
      </p>
    </section>

    <section>
      <h2>14. Force Majeure</h2>
      <p>
        Notwithstanding anything contained herein or the Privacy Policy or any other applicable policy,
        VetanNow shall under no circumstances be held liable for any damages, losses, loss of Products
        and Services etc. resulting directly or indirectly from causes beyond its reasonable control,
        including, without limitation, acts of nature, failures of internet or computer/telecom equipment,
        change in regulations such as Reserve Bank of India regulations, or other government regulations,
        riots, epidemics, storms, civil disturbances, floods etc.
      </p>
    </section>

    <section>
      <h2>15. Termination</h2>
      <p>
        The agreement is effective until terminated by You or VetanNow. You can terminate this agreement
        at any time by closing the user account and no longer accessing or using the VetanNow platform or
        Products and Services.
      </p>
      <p>
        Your rights under this agreement will terminate without notice if You fail to comply with or
        breach any of the Terms of Use or any other policies including but not limited to Privacy Policy
        or it is discovered that you are not eligible to use the VetanNow platform.
      </p>
      <p>
        Upon termination of the License, You shall cease all use of the VetanNow platform and Products and
        Services and destroy all copies, full or partial, of the VetanNow platform. In case of any
        termination by either You or VetanNow or in case of deletion, uninstallation, discontinuation of
        use of the VetanNow platform, You will not be absolved from your obligation and liability of
        repaying the outstanding dues including but not limited to the amount of the Salary/Earned Amount
        Advance Facility, interest accrued thereon as per the Salary/Earned Amount Advance Facility
        Documents and the Transaction Fees, to the NBFC nor any rights of recovery in relation thereto
        would be waived.
      </p>
    </section>

    <section>
      <h2>16. Governing Law, Jurisdiction and Arbitration</h2>
      <ol>
        <li>
          The formation and interpretation of these Terms of Use, Privacy Policy or any other applicable
          policy and any disputes arising in relation thereto shall be governed by the substantive and
          procedural laws of India. Courts at Navi Mumbai, Maharashtra, India shall have exclusive
          jurisdiction in or in relation to any matter arising under the present Terms of Use or connected
          policies including but not limited to the Privacy Policy.
        </li>
        <li>
          In the event of disputes, differences or claims arising out of or in connection with these Terms
          of Use and/or the other applicable policies including but not limited to Privacy Policy or in
          any way relating hereto or any term, condition or provision herein mentioned or the construction
          or interpretation thereof or otherwise in relation thereto, VetanNow and You shall first endeavor
          to settle such differences, disputes or claims by amicable settlement and failing such
          settlement, the same shall be resolved by arbitration by a sole Arbitrator to be appointed
          mutually by VetanNow and You. The arbitration proceedings shall be held in accordance with the
          Arbitration and Conciliation Act, 1996 or any statutory modification or re-enactment thereof for
          the time being in force. The place of Arbitration shall be Navi Mumbai and the proceedings shall
          be conducted in the English language.
        </li>
      </ol>
    </section>

    <section>
      <h2>17. Amendments and Modifications</h2>
      <p>
        VetanNow reserves the right to modify this Terms of Use or policies including but not limited to
        Privacy Policy relating to the VetanNow platform or Products and Services at any time, effective
        upon posting of an updated version of this Terms of Use or the said policies, as the case may be,
        on the VetanNow platform. Upon doing so, the revised updated date shall be reflected at the bottom
        of the page containing the Terms of Use or the said policies. Continued use of the VetanNow
        platform or Products and Services after any such changes shall constitute your consent to such
        changes to the Terms of Use or said policies.
      </p>
    </section>

    <section>
      <h2>18. Refund and Cancellation Policy</h2>
      <p>
        VetanNow may offer non-lending/non-regulated products directly on the platform. Please note, once
        the customer has confirmed an order for purchase or sale, refunds or cancellation is not possible.
        All orders are final upon customer confirmation.
      </p>
    </section>

    <section>
      <h2>19. Mechanism for Grievance Redressal</h2>
      <p>Grievance Officer details:</p>
      <p>
        VetanNow
        <br />
        E-mail: <a href="mailto:support@vetannow.com">support@vetannow.com</a>
        <br />
        Contact Number: <a href="tel:+919579861176">9579861176</a>
      </p>
    </section>
  </LegalPage>
);

export default TermsOfUse;
